spring:
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/master.yaml
    default-schema: catalogue
    liquibase-schema: catalogue

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/postgres?currentSchema=${SCHEMA:catalogue}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always


